### ISSUE TITLE
Resen presentation CEDAR feedback

### ISSUE THREAD

**Issue by asreimer** [EarthCubeInGeo/resen-core#26]
- sudo (or equivalent) access for users to install packages with apt-get.
- include support for other languages, such as C? Which language was not specified.
- using dask? this should just work if installed, but doesn't scale unless docker does.
- install pysat, mivit
- can this use GPUs?

**Comment by ljlamarche** [comment]
In regards to installing pysat:
Currently there appears to be an issue with the parts of pysat that wrap FORTRAN.
The following appears to work:
1. `git clone https://github.com/rstoneback/pysat.git`
2. In pysat directory, remove the dependence on `pysatCDF` and `pysatMagVect` (make sure you get both places).
3. Install with `python setup.py install`.
This produces a working version of pysat, but it will not have CDF4 reading capabilities.

**Comment by asreimer** [comment]
Hmm. We will have to play with the installation a bit. There shouldn't be any reason why one cannot use `pip install .` so if that isn't working we might need to modify the `pysat setup.py` and make a PR for that project.

Since there's a theme of dumping on davitpy this week, "Even davitpy can be installed with `pip install .`!" :)

**Comment by ljlamarche** [comment]
To be honest I didn't try `pip install .`  Russell recommended using `python setup.py install` so that's what I was going off off...  I should probably try that to see if it varies the behavior at all.

**Comment by asreimer** [comment]
Revisiting this, I think the feedback can be addressed as follows:
- sudo can/should be given by resen cmd line tool on bucket creation (by default?) but not for server
- support for other languages, either as an "add-on install script" that we can provide or as custom resen-core-extras-* style docker images that we provide
- GPUs and Dask, we'll have to just test this ourselves, but this should be low priority for now.
- Can we install <insert favorite python package here>? Yes, but only if it doesn't balloon the resen-core image size (easy example, pysat pulls in torch and torch is ~800MB). We can work with package developers to limit package size/dependencies and/or provide "add-on scripts" that the user can decide to run to install additional packages with.

Maybe this "addon" idea could be another repository? Then we can add/update scripts in this repo and have it by default included in resen-core. A user would simply `git pull origin` and then run the script that installed what they need?

Discuss? What does everyone think?

**Comment by ljlamarche** [comment]
I'm going to be working on the sudo issue as part of the general refactoring of the resen tool, so that one will hopefully be resolved soon (EarthCubeInGeo/resen#40).

I'm not really sure what the thought was for supporting other languages...  If we're talking about just C or FORTRAN, we can install `gcc` or `gfortran`, but I don't know what it will do to the image size.  Installing every library under the sun is probably a bad idea, but don't we have some of them in there already for things like numpy?

A slight variation to the "addon" idea is that we build some kind of "addon manager" as a utility that's included in resen-core.  This would probably essentially just be a dictionary of different `wget` commands that retrieves ONLY the most up-to-date add on script that a user is interested in and runs it.  This might be a cleaner user experience because there won't be a "addon-scripts" directory floating around and users don't need to know anything about `git`, but the trade off of course is that they DO need to know about our custom tool.
